version: '3'

services:

  postgresql:
    image: postgres:14.3
    container_name: postgresql
    environment:
      PGSQL_USER: admin
      PGSQL_PASSWORD: admin
      PGSQL_DATABASE: taskdb
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data

  django:
    build: .
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8002"
    container_name: invera_tasks
    volumes:
      - .:/app
      - ./data:/var/lib/postgresql/data
    environment:
      PGSQL_HOST: postgresql
      PGSQL_DATABASE: taskdb
      PGSQL_USER: admin
      PGSQL_PASSWORD: admin
    ports:
      - "8002:8002"
    depends_on:
      - postgresql
    links:
      - postgresql

volumes:
  data:
